### ISSUE TITLE
give the app the ability to transfer downloads

### ISSUE THREAD

**Issue by Korygauger** [KotatsuApp/Kotatsu#1099]
### Describe your suggested feature

I have downloaded a ton of manga through this app with the intention of transferring these downloads to my PC but I can't access the original download folder via the file manager and changing the location of my downloads doesn't change the location of files already downloaded. I also can't delete them easily and re-download due to the same issue of being unable to access the location via a file manager. I would very much appreciate there being an option of moving manga around.

### Acknowledgements

- [X] This is not a duplicate of an existing issue. Please look through the list of [open issues](https://github.com/KotatsuApp/Kotatsu/issues) before creating a new one.

**Comment by NA0341** [comment]
You can just select Manga in the Local Manga section, tap the Share Button and share them with a file sharing solution or something of the sort.

For example, you could share it with KDE-Connect to transfer them directly to your PC via your local network.

---

If that doesn't work for You:

The simplest approach to this would probably be an `Export` entry in the three dots menu in the `Local storage` UI.

Tapping on `Export` opens a pop up menu of the following options:

+ Buttons for each configured Storage Location ~ to open the location in the file manager with Kotatsu's permission to access the folder (via Androids file access API for example ~ needs file manager support).
+ »Select Manga« option which allows for batch actions.

Batch actions:
+ Share (already implemented)
+ Export (manually as Archive ~ optionally change format between multiple & single cbz file).

The export batch action would be a last resort if everything else fails to work.


I'm on Android 9 and therefore still have access to all these folders. I manually edit saved manga quite regularly to improve my local copies. So I can confirm that access to the manga files is very important & useful.

This is an issue with Android itself. Mainly because Google has a tendency to restrict it's products as they develop ~ with the claim that it is for the users safety.

...and Android ist just one of these products that Google continuously messes with..

**Comment by Korygauger** [comment]
@NA0341 that worked thanks. I think I'll change my OS to Calyx soon to see if they will let me access this stuff
