### ISSUE TITLE
Material You - Dynamic theme

### ISSUE THREAD

**Issue by kalekad** [KotatsuApp/Kotatsu#237]
Kotatsu v4 - all releases
LineageOS 19.1 - Android 12L

The dynamic theme does not show up in the app no matter what theme option I choose in the settings.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by Koitharu** [comment]
https://github.com/material-components/material-components-android/issues/2677

**Comment by ztimms73** [comment]
ROM issue

**Comment by Koitharu** [comment]
I think we should also enable this option for LineageOS

**Comment by ztimms73** [comment]
Is there an option to enable a dynamic theme in the device settings? Does the theme change in apps like Google Phone, Google Messages? You can download an app called M3 Catalog, which has option to enable dynamic theme: https://github.com/material-components/material-components-android/releases/tag/1.7.0-rc01

Be sure to download 1.7.0-rc01, because we are using this version of design library in Kotatsu

**Comment by ztimms73** [comment]
Then after you have installed the application, make sure that there is an option to enable dynamic theme (example in the screenshot)

![Screenshot_20221013-175102](https://user-images.githubusercontent.com/61558546/195632568-f9572909-a030-4f82-af83-29ee0170d82d.png)

**Comment by Koitharu** [comment]
Material You engine becomes a part of AOSP in A13. In A12 it was a vendor-specific feature, available on Google Pixel and some other devices

**Comment by ztimms73** [comment]
reopen if there are any questions

**Comment by PhilippKosarev** [comment]
The dynamic theme does not work for me even though the linked Material demo does.

OneUI version: 6.0
Android version: 14
Kotatsu version: 7.0.1

Kotatsu vs Tachiyomi, both set to Dynamic Theme:
![ResizedImage_2024-05-29_00-59-12_1425](https://github.com/KotatsuApp/Kotatsu/assets/102914158/e0daf52d-0163-47cf-a0a3-0e1b2b9dd20e)
