### ISSUE TITLE
There's no option to mark a chapter as read.

### ISSUE THREAD

**Issue by Loughty** [KotatsuApp/Kotatsu#56]
That's a basic and good feature to have a control of what you see and what not.

Another thing it's having two colors to difference: the red to mark a chapter that you're reading (but not complete yet), and the green to mark something that you complete read.

Thanks a lot, pals.

**Comment by b0ywearngtights** [comment]
Having something similar to mark downloaded chapters would be nice !

**Comment by nv95** [comment]
This is no way to know is chapter is read or not. It just highlighted according to your reading history (last read chapter)

It is this option really needed? Can you provide some use cases for it?

**Comment by BaccanoMob** [comment]
I think the initial comment would be difficult to implement if the reader does not keep track of the pages read.

Also, I think it would be good idea to implement a forced last read chapter status. For example, i read a few chapters from my PC or other devices then I can long press the latest chapter from the app and choose an option "Mark last read" (I am assuming you do not have plans to implement chapterwise read status and only relay on reading history). This will be useful so you dont download unnecessarily of the last chapter (like if a chapter has 60+ pages). 


> It would be nice to have something similar to mark downloaded chapters in the favorites library, not just in the local storage library where non-downloaded chapters are grayed out.
@b0ywearngtights I think you pretty much can clearly differentiate between download and non-downloaded chapters as you say being grayed out and not. Unless you mean something else differently

**Comment by b0ywearngtights** [comment]
Left is in the "local storage" tab and right is the same manga but opened from the "favorites" tab, the first clearly shows which chapter is downloaded or not but it is not the case in the favorites tab.

![untitled](https://user-images.githubusercontent.com/94209903/152351581-14ea313a-246e-43c5-990f-76fe74281a2e.png)

There is something weird because it's not happening with all my manga, some are correctly shown even in the favorites tab.

![unti](https://user-images.githubusercontent.com/94209903/152358397-bafa816e-e186-4871-9385-41cf292037e1.png)

The difference between these two manga is that in the first one the source is still indicated.
