### ISSUE TITLE
Extension requests

### ISSUE THREAD

**Issue by yamsonyanyan** [KotatsuApp/Kotatsu#656]
### Describe your suggested feature

Can the developer add hentai2read extension?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by hullmat998** [comment]
This has already been requested back in October. You probably didn't find it since source requests are treated as a seperate issues page almost. Instead of clicking "features" when making a new issue post; you need to click the next one down. 

https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose

**Comment by kyoyacchi** [comment]
https://github.com/KotatsuApp/kotatsu-parsers/issues/311
