### ISSUE TITLE
MangaFire blocking solution found

### ISSUE THREAD

**Issue by Mhuzaifakhalid** [KotatsuApp/Kotatsu#948]
### Describe your suggested feature

I started using MangaFire a month ago or so. But after a few days, the source blocked me whenever I downloaded something. I really really love it and so do many other users. I've seen the same complaint in the discord discussion as well. I've attached the Screenshot of the error as well. 

But today I observed that whenever I'm blocked and I open any manga from that source in webmode, it does some verification saying "WAF" and the website works in the webmode even when not working in the app. 

But here's the thing, when the website is loaded in the webmode, it starts working in the app as well. If it stops working again, opening it in the webmode solves it for some time. So I thought maybe the devs could use this info and do something about it as MangaFire is THE BEST source for me and many many other users. 

Thanks (sorry for the bad English)
![Screenshot_20240627_211140_Kotatsu](https://github.com/KotatsuApp/Kotatsu/assets/173570485/ba03db7f-f580-46b1-93cb-eb6e62779a6f)

### Acknowledgements

- [X] This is not a duplicate of an existing issue. Please look through the list of [open issues](https://github.com/KotatsuApp/Kotatsu/issues) before creating a new one.

**Comment by galpt** [comment]
So I tried to debug the website (`mangafire.to`) myself like some days ago, and noticed that this website has some javascript auto-redirecting to the homepage.

You can reproduce it by opening the web on a laptop/desktop browser, and open **Inspect Elements**.
Try to go to other page (i.e. `https://mangafire.to/type/manga`) with the Inspect Elements still open, and you'll be redirected to `https://mangafire.to/` again.

This can also be triggered if you're using AdBlocker, in my case I use Adblock Plus extension for Chrome.

I guess this could give another clue why Kotatsu failed to parse the html properly.
The error message shows that Kotatsu couldn't find `".info > h1"` which I believe are some HTML classes.

I'd say this issue is more like a parser issue, but the devs will need to investigate it themselves.

**Comment by ztimms73** [comment]
Open ticket in parsers repo

**Comment by Mhuzaifakhalid** [comment]
> Open ticket in parsers repo

What does that mean?

**Comment by galpt** [comment]
This is more like an issue with the parser, so it's not really a bug from the kotatsu app, it's caused by the website we're trying to use (in this case MangaFire), so that's why I think it's more like a parser issue.

So this issue should be discussed on the parser repo, not here..
https://github.com/KotatsuApp/kotatsu-parsers/issues

**Comment by Mhuzaifakhalid** [comment]
> This is more like an issue with the parser, so it's not really a bug from the kotatsu app, it's caused by the website we're trying to use (in this case MangaFire), so that's why I think it's more like a parser issue.
> 
> So this issue should be discussed on the parser repo, not here.. https://github.com/KotatsuApp/kotatsu-parsers/issues

Okay
